// src/routes/services/+page.svelte
<svelte:head>
  <title>Services</title>
  <meta name="description" content="Website design, frontend build, and performance work for growing businesses." />
</svelte:head>

<h1>Services</h1>
<p>Website design, frontend build, and performance work for growing businesses.</p>

<ul>
  <li>Design and prototyping</li>
  <li>SvelteKit and React builds</li>
  <li>Core Web Vitals tuning</li>
</ul>

// src/pages/Services.jsx
export default function Services() {
  return (
    <section>
      <h1>Services</h1>
      <p>Website design, frontend build, and performance work for growing businesses.</p>
      <ul>
        <li>Design and prototyping</li>
        <li>React and SvelteKit builds</li>
        <li>Core Web Vitals tuning</li>
      </ul>
    </section>
  );
}
