// pages/services.vue
<script setup>
useSeoMeta({
  title: 'Services',
  description: 'Website design, frontend build, and performance work for growing businesses.'
})
</script>

<template>
  <section>
    <h1>Services</h1>
    <p>Website design, frontend build, and performance work for growing businesses.</p>
    <ul>
      <li>Design and prototyping</li>
      <li>Nuxt and React builds</li>
      <li>Core Web Vitals tuning</li>
    </ul>
  </section>
</template>

// src/pages/Services.jsx
export default function Services() {
  return (
    <section>
      <h1>Services</h1>
      <p>Website design, frontend build, and performance work for growing businesses.</p>
      <ul>
        <li>Design and prototyping</li>
        <li>React and SvelteKit builds</li>
        <li>Core Web Vitals tuning</li>
      </ul>
    </section>
  );
}
