// src/routes/contact/+page.svelte
<svelte:head>
  <title>Contact Us</title>
  <meta name="description" content="Tell us about your project and we will get back to you within two business days." />
</svelte:head>

<h1>Contact Us</h1>
<p>Tell us about your project and we will get back to you within two business days.</p>

<address>hello@northwind.example</address>

// pages/contact.vue
<script setup>
useSeoMeta({
  title: 'Contact Us',
  description: 'Tell us about your project and we will get back to you within two business days.'
})
</script>

<template>
  <section>
    <h1>Contact Us</h1>
    <p>Tell us about your project and we will get back to you within two business days.</p>
    <address>hello@northwind.example</address>
  </section>
</template>
